version: '2.2'
services:
  postgres:
    image: postgres:latest
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment:
        POSTGRES_DB: hq_api_development
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
volumes:
  data01:
    driver: local
networks:
  elastic:
    driver: bridge
